### PR TITLE
project restructuring required for committee like consensus creation

### LINKED ISSUE #30: Align structure of truechain-consensus-core with py-trueconsensus
For the sake of verbosity, here's the salvation of discussion from https://github.com/truechain/truechain-consensus-core/pull/10#issuecomment-395396551

---

The current aim for this repo is to have a modularized consensus, which would very soon be integrated into go-ethereum's fork of truechain as per https://github.com/truechain/truechain-consensus-core/milestone/2

Eventually the bft committee in hybrid consensus would need PBFT code in a separate package and `HyperMake` should modified to build the entire modularized consensus itself, rather than just PBFT.

---

Here's what I have in my head:

```
.
├── docs/
│   ├── DEV.md
│   └── TODO.md
├── HyperMake
├── LICENSE
├── trueconsensus/ (code for hybrid consensus)
│   ├── cmds
│   │   └── main.go [calls both fast and snailchain]
│   ├── fastchain/ *
│   ├── slowchain/ **
│   ├── config.yaml ***
│   ├── bft_committee.cfg ****
│   └── vendor/
│       └── manifest
├── README.md
├── support/
│   ├── scripts/
│   └── toolchain/
└── tests
    ├── core-consensus
```

- `* fastchain/` (contains current PBFT codebase as currently under src/pbft/)
- ` ** slowchain/` is the snailchain in our hybrid consensus, a POW variant called fruitchain, which for this development purpose, is going to be a dummy block producer. 
- `*** config.yaml` contains node environment settings, tunables, etc.. just like https://github.com/truechain/truechain-consensus-core/issues/11 
- `**** bft_committee.cfg` contains log directory path, network config paths and so on..

---

FYI 

This derives design decisions from https://github.com/truechain/py-trueconsensus (parallel effort, initial faster prototyping but supposed to be maintained separately)

This slowchain is responsible for electing BFT committee, so essentially for single node testing purpose, we'd have multiple instances of slowchain and fastchain, all interacting through gRPC interfaces. The number of fastchain instances would be controlled by a tunable specified under `config.yaml`
---

### PR DESCRIPTION
**Pull request by arcolife**
fixes #30 -> init bft committee: re-align project structure

add init package in manifest

### CODE REVIEW

**Comment by arcolife** [comment]
WIP:

1. smoke tests + travis CI yml integration
2. config yml - wrap #10 and #14 into this PR 
3. wrap readme content from #22 into this for logging

**Review by samikshan — COMMENTED** [review]
Changes to be made:
- Installation
- Readme
- ini in manifest

**Comment by arcolife** [comment]
++

- hmake build test 
- push new image to dockerhub from #27 fix
- create a release ?

**Comment by arcolife** [comment]
Code runs fine. 
opened #64 to track a test failure separately
will create a release once 64 is fixed. 

have pushed docker image to https://hub.docker.com/r/truechain/toolchain/tags/ cc/ @hixichen

**Pull request merged**
