### PR TITLE
structure the code with hmake, go-toolchain and dependency managerment

### PR DESCRIPTION
**Pull request by hixichen**
- add hmake to make build simple:
   how to use:
       - brew install hmake
       - hmake --targets
       - hmake build

- add golang toolchain:
    - specific the golang version
    - if not exist, will build with Dockfile
    - toolchain name: truechain/go-toolchain

- add dependency managerment via gvt

    fixed version of dependency packages

what is more: hmake check
    - go lint
    - go fmt

### CODE REVIEW

**Comment by hixichen** [comment]
Please review this CR to make the build simple.

**Comment by arcolife** [comment]
on it. :+1:

**Comment by hixichen** [comment]
any feedback?

**Comment by arcolife** [comment]
yeah hmake looks like a good tool. I'm merging this now and making some additional changes:

- lint fails obviously due to lack of comments
- I added https://hub.docker.com/r/truechain/go-toolchain/
- build passed (locally, not in container) only when we do this ```export GOPATH=$GOPATH:`pwd`:`pwd`/..```. So we need to pull in the dependencies.  This is where it would fail:

```
[build-linux]       src/pbft-core/node.go:29:2: cannot find package "github.com/alecthomas/repr" in any of:
[build-linux]       	/usr/local/go/src/github.com/alecthomas/repr (from $GOROOT)
[build-linux]       	/go/src/github.com/alecthomas/repr (from $GOPATH)
[build-linux]       	/src/src/github.com/alecthomas/repr
[build-linux]       	/src/src/github.com/alecthomas/repr
[build-linux]       	/src/github.com/alecthomas/repr
[build-linux]       src/pbft-core/utils.go:21:2: cannot find package "github.com/fatih/color" in any of:
[build-linux]       	/usr/local/go/src/github.com/fatih/color (from $GOROOT)
[build-linux]       	/go/src/github.com/fatih/color (from $GOPATH)
[build-linux]       	/src/src/github.com/fatih/color
[build-linux]       	/src/src/github.com/fatih/color
[build-linux]       	/src/github.com/fatih/color
```

- rest, we need to make sure hmake is widely adopted enough. I asked a couple of golang devs here in my local community and they don't use it yet. We could always change it later. `devel` branch is meant for experiments. Lets keep it in there and merge in master when everything is

**Comment by hixichen** [comment]
I am sorry that the .gitignore file had filter the vendor/manifest file. 


I pushed a new change to fix this. 

After this change, you should be abale do:

$hamke build

after merger the fix, please update the readme file. 

- use gvt to manage the dependency
- use hmake to interactive with toolchain and build binary

**Pull request merged**
